#!/bin/bash
## resources:
## https://github.com/AndrewFromMelbourne/raspberry_pi_revision
## http://elinux.org/RPi_HardwareHistory#Board_Revision_History
## https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md
## https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/revision-codes/README.md

Revision=$(cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}')
Encoded=$((0x$Revision >> 23 & 1))

if [ $Encoded = 1 ]; then
    ModelName=('A' 'B' 'A+' 'B+' 'Pi2B' 'Alpha' 'CM1' 'unknown' '3B' 'Zero' 'CM3' 'unknown' 'Zero W' '3B+' '3A+' 'internal use only' 'CM3+' '4B' '18 ?' '19 ?' '20 ?')
    echo ${ModelName[$((0x$Revision>>4&0xff))]}
fi
